/*
Algorithm:
  - const initialOffset = 15s
  - polling time after initialOffset = 15s

  - global object: const normalizedTimestamps = config.timestamps;
  [130, 145, 160, 175]

  - inside the while loop: (polling every 15s)
      - if (normalizedTimstamps.length === 1) {
        break
      }
      - calculate the lowerBound & upperBound of normalizedTimestamps[0]
      - let shouldProcess = false
      - loop through each json file generated by weather-station
          - if the stepStartTime >= upperBound {
              shouldProcess = true
              break
            }
          - else continue
      - if (shouldProcess) {
        - only process all data points in normalizedTimestamps[0] (delete it after process as well)
          - only data points with stepStartTime between lowerBound & upperBound (>=lowerBound & < upperBound)
        - send only the data points from  normalizedTimestamps[0] to S3 bucket
        - reset buckets, filteredBucket, and finalBucket 
        - chop off the normalizedTimestamps[0] -> [145, 160, 175]
      }
  - await sleep(15s) -> process the last batch


*/
